services:
  backend:
    build: backend
    volumes:
      - ./backend:/app:cached
    working_dir: /app
    env_file:
      - .env

  worker:
    image: registry.andyi95.com/social-dashboard/backend:v0.1
    build: backend
    command: python services/worker.py && python services/word_parser.py
    env_file:
      - .env

  frontend:
    build:
      context: frontend
      dockerfile: stage.Dockerfile