# Generated by Django 4.2.4 on 2023-08-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deactivated', models.BooleanField(blank=True, null=True)),
                ('is_closed', models.BooleanField(blank=True, null=True)),
                ('about', models.CharField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('bdate', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_comment='Publication timestamp in MSC tz', null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('screen_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_closed', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_id', models.IntegerField(blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('social_media_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='тип соц. сети')),
            ],
            options={
                'db_table': 'group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, db_comment='Publication timestamp in MSC tz', null=True)),
                ('marked_as_ads', models.BooleanField(blank=True, null=True)),
                ('post_type', models.CharField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('likes_count', models.IntegerField(blank=True, null=True)),
                ('repost_count', models.IntegerField(blank=True, null=True)),
                ('views_count', models.IntegerField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poststats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField()),
                ('repost_count', models.IntegerField()),
                ('views_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
            ],
            options={
                'db_table': 'poststats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, db_comment='Publication date of original post in MSC tz', null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'postword',
                'managed': False,
            },
        ),
    ]
