# Generated by Django 4.2.4 on 2023-12-11 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"managed": True, "verbose_name": "Social Media Account"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"managed": True, "verbose_name": "Social Media Group"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"managed": True, "verbose_name": "Social Media Post"},
        ),
        migrations.AlterModelOptions(
            name="poststats",
            options={"managed": True, "verbose_name": "Social Media Post Stats"},
        ),
        migrations.AlterModelOptions(
            name="postword",
            options={"managed": True, "verbose_name": "Word in Social Media Post"},
        ),
    ]
