# Generated by Django 4.2.4 on 2023-12-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_account_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="from_field",
            field=models.ForeignKey(
                blank=True,
                db_column="from_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.account",
                verbose_name="ID of comment author",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.group",
                verbose_name="ID of group feed with the comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.post",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="posts",
                to="dashboard.group",
            ),
        ),
        migrations.AddField(
            model_name="poststats",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="stats",
                to="dashboard.post",
            ),
        ),
        migrations.AddField(
            model_name="postword",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="words",
                to="dashboard.post",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="about",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Publication timestamp in MSC tz"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Publication timestamp in MSC tz"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="postword",
            name="date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Publication date of original post in MSC tz",
            ),
        ),
    ]
