# Generated by Django 4.2.4 on 2023-12-11 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_comment_from_field_comment_owner_comment_post_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poststats",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
