# Generated by Django 4.2.4 on 2023-12-11 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_poststats_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "managed": True,
                "ordering": ("first_name", "last_name"),
                "verbose_name": "Social Media Account",
            },
        ),
        migrations.AlterModelOptions(
            name="group",
            options={
                "managed": True,
                "ordering": ("name", "id"),
                "verbose_name": "Social Media Group",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "managed": True,
                "ordering": ("date", "id"),
                "verbose_name": "Social Media Post",
            },
        ),
        migrations.AlterModelOptions(
            name="poststats",
            options={
                "managed": True,
                "ordering": ("created_at", "id"),
                "verbose_name": "Social Media Post Stats",
            },
        ),
        migrations.AlterField(
            model_name="poststats",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
