# Generated by Django 4.2.4 on 2024-02-11 10:55

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_account_options_alter_group_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="tag")),
                ("description", models.TextField(verbose_name="tag description")),
            ],
            options={
                "verbose_name": "post tag",
                "verbose_name_plural": "tags",
            },
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("name"),
                name="unique_lower_name",
            ),
        ),
    ]
