# Generated by Django 4.2.4 on 2024-02-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_tag_tag_unique_lower_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("date", "id"), "verbose_name": "Social Media Post"},
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="dashboard.tag"
            ),
        ),
    ]
