# Generated by Django 4.2.4 on 2025-03-22 08:18

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_alter_post_options_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "managed": True,
                "ordering": ("date", "id"),
                "verbose_name": "Social Media Post",
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                django.db.models.functions.datetime.Trunc("date", "day"),
                name="post_date_date_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                models.F("id"), models.F("date"), name="unique_id_date"
            ),
        ),
    ]
