# Generated by Django 4.2.4 on 2025-03-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_alter_post_options_post_post_date_date_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
