# Generated by Django 4.2.4 on 2025-03-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0010_alter_comment_id_alter_group_group_id_alter_group_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PostHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="dashboard.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post History",
                "verbose_name_plural": "Post Histories",
            },
        ),
    ]
