# Generated by Django 4.2.4 on 2025-03-23 16:01

from django.db import migrations, models
import django.db.models.deletion

def migrate_tags(apps, schema_editor):
    Post = apps.get_model("dashboard", "Post")
    Tag = apps.get_model("dashboard", "Tag")
    PostTag = apps.get_model("dashboard", "PostTag")

    for post in Post.objects.filter(tags__isnull=False):
        for tag in post.tags.all():
            PostTag.objects.create(post=post, tag=tag, tagged_at=post.created_at)


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_posthistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "tag", "verbose_name_plural": "tags"},
        ),
        migrations.CreateModel(
            name="PostTag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tagged_at",
                    models.DateTimeField(null=True, verbose_name="tagged at"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.post",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Tag",
                "verbose_name_plural": "Post Tags",
            },
        ),
        migrations.RunPython(migrate_tags, reverse_code=migrations.RunPython.noop),
    ]
