# Generated by Django 4.2.4 on 2025-03-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0012_alter_tag_options_posttag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tags",
            new_name="tags_old",
        ),
        migrations.AlterField(
            model_name="post",
            name="tags_old",
            field=models.ManyToManyField(
                blank=True, related_name="posts_old", to="dashboard.tag"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                through="dashboard.PostTag",
                to="dashboard.tag",
            ),
        ),
    ]
