# Generated by Django 4.2.4 on 2023-10-08 10:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("content", tinymce.models.HTMLField(verbose_name="content")),
                ("date", models.DateField(verbose_name="entry date")),
            ],
            options={
                "verbose_name": "article entry",
                "verbose_name_plural": "articles entries",
            },
        ),
    ]
