#!/bin/sh

set -e

ENV_FILE=".env"

# Function to add or update a variable in the .env file
add_or_update_env() {
    local var_name=$1
    local var_value=$2

    if grep -q "^$var_name=" "$ENV_FILE"; then
        # Variable exists, update it
        sed -i "s/^$var_name=.*/$var_name=$var_value/" "$ENV_FILE"
    else
        # Variable does not exist, add it
        echo "$var_name=$var_value" >> "$ENV_FILE"
    fi
}

# Check if the .env file exists
if [ ! -f "$ENV_FILE" ]; then
    touch "$ENV_FILE"
fi

add_or_update_env "COMPOSE_FILE" "docker-compose.yaml:docker-compose.stage.yaml"
add_or_update_env "COMPOSE_PROJECT_NAME" "social-dashboard"
add_or_update_env "TAG" "${CI_COMMIT_SHORT_SHA}"
add_or_update_env "GOOGLE_APPLICATION_CREDENTIALS" "/app/gcloud-service-key.json"
add_or_update_env "CI_REGISTRY_IMAGE" "registry.andyi95.com/social-dashboard/backend"
add_or_update_env "AUTH_PASSWRD" "${AUTH_PASSWRD}"
echo "Updated .env file with the necessary variables."
