# Generated by Django 4.2.4 on 2023-12-11 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_networks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={
                "ordering": ("-expires_at",),
                "verbose_name": "Access token",
                "verbose_name_plural": "Access tokens",
            },
        ),
    ]
