# Generated by Django 4.2.4 on 2025-03-22 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("social_networks", "0002_alter_token_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="social media account id",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="token",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
