"""empty message

Revision ID: fbe597285cfa
Revises: 
Create Date: 2022-08-02 12:42:11.709357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe597285cfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('deactivated', sa.Boolean(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('activities', sa.Text(), nullable=True),
    sa.Column('bdate', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('screen_name', sa.String(length=255), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True, comment='Publication timestamp in MSC tz'),
    sa.Column('marked_as_ads', sa.Boolean(), nullable=True),
    sa.Column('post_type', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('repost_count', sa.Integer(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_owner_id'), 'posts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_posts_post_id'), 'posts', ['post_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=True, comment='ID of comment author'),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='ID of group feed with the comment'),
    sa.Column('date', sa.DateTime(), nullable=True, comment='Publication timestamp in MSC tz'),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_owner_id'), 'comments', ['owner_id'], unique=False)
    op.create_table('posts_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=255), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True, comment='Publication date of original post in MSC tz'),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_words_id'), 'posts_words', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_words_id'), table_name='posts_words')
    op.drop_table('posts_words')
    op.drop_index(op.f('ix_comments_owner_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_posts_post_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_owner_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('groups')
    op.drop_table('accounts')
    # ### end Alembic commands ###
